image: echothree/build:latest

variables:
  ANT_OPTS: "-Xmx5120m"

stages:
  - build

build:
  stage: build
  script:
    - pushd ..
    - ln -s $WILDFLY_HOME wildfly-latest
    - popd
    - ant setup-ivy
    - ant complete
  artifacts:
    paths:
      - echothree/build/ears/echothree.ear
      - echothree/build/jars/echothree-client.jar
      - echothree/build/lib/mysql-connector-java.jar
      - echothree/build/ui/web/cms/war/cms.war
      - echothree/build/ui/web/letter/war/letter.war
      - echothree/build/ui/web/main/war/main.war
      - echothree/build/service/graphql/war/graphql.war
      - echothree/build/service/job/jar/echothree-job.jar
    expire_in: 1 week

