ALTER TABLE itemharmonizedtariffschedulecodedetails DROP FOREIGN KEY itmhztscdt_itm_itemid_fk;
ALTER TABLE itemharmonizedtariffschedulecodedetails DROP FOREIGN KEY itmhztscdt_hztsc_harmonizedtariffschedulecodeid_fk;

DROP INDEX index2_idx ON itemharmonizedtariffschedulecodedetails;
DROP INDEX index5_idx ON itemharmonizedtariffschedulecodedetails;

ALTER TABLE itemharmonizedtariffschedulecodedetails ADD COLUMN itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid BIGINT;

UPDATE itemharmonizedtariffschedulecodedetails SET itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid = (SELECT hztscutyp_harmonizedtariffschedulecodeusetypeid FROM harmonizedtariffschedulecodeusetypes, harmonizedtariffschedulecodeusetypedetails WHERE hztscutyp_activedetailid = hztscutypdt_harmonizedtariffschedulecodeusetypedetailid AND hztscutypdt_harmonizedtariffschedulecodeusetypename = 'EXPORT');

ALTER TABLE itemharmonizedtariffschedulecodedetails MODIFY COLUMN itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid BIGINT NOT NULL;

ALTER TABLE itemharmonizedtariffschedulecodedetails ADD UNIQUE KEY index2_idx (itmhztscdt_itm_itemid, itmhztscdt_countrygeocodeid, itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid, itmhztscdt_thrutime);
ALTER TABLE itemharmonizedtariffschedulecodedetails ADD KEY index5_idx (itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid, itmhztscdt_thrutime);
ALTER TABLE itemharmonizedtariffschedulecodedetails ADD KEY index6_idx (itmhztscdt_hztsc_harmonizedtariffschedulecodeid, itmhztscdt_thrutime);

ALTER TABLE itemharmonizedtariffschedulecodedetails ADD CONSTRAINT itmhztscdt_itm_itemid_fk FOREIGN KEY (itmhztscdt_itm_itemid) REFERENCES items(itm_itemid) ON DELETE CASCADE;
ALTER TABLE itemharmonizedtariffschedulecodedetails ADD CONSTRAINT itmhztscdt_hztsc_harmonizedtariffschedulecodeid_fk FOREIGN KEY (itmhztscdt_hztsc_harmonizedtariffschedulecodeid) REFERENCES harmonizedtariffschedulecodes(hztsc_harmonizedtariffschedulecodeid) ON DELETE CASCADE;
ALTER TABLE itemharmonizedtariffschedulecodedetails ADD CONSTRAINT itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid_fk FOREIGN KEY (itmhztscdt_hztscutyp_harmonizedtariffschedulecodeusetypeid) REFERENCES harmonizedtariffschedulecodeusetypes(hztscutyp_harmonizedtariffschedulecodeusetypeid) ON DELETE CASCADE;
