// --------------------------------------------------------------------------------
// Copyright 2002-2026 Echo Three, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------------------

package com.echothree.model.control.index.common;

public enum IndexFields {

    address1,
    address2,
    address3,
    aliases,
    allowAssociatePayments,
    allowClubDiscounts,
    allowCouponDiscounts,
    allowSolicitation,
    appearance,
    areaCode,
    attention,
    city,
    cityGeoCodeName,
    companyName,
    componentVendorName,
    contactMechanismName,
    contactMechanismPurposeNames,
    contactMechanismTypeName,
    contentCatalogName,
    contentCategoryName,
    contentCategoryNames,
    contentCollectionName,
    country,
    countryGeoCodeName,
    county,
    countyGeoCodeName,
    createdTime,
    currencyIsoName,
    customerName,
    customerTypeName,
    deletedTime,
    description,
    emailAddress,
    entityAliasTypeName,
    entityAttributeGroupName,
    entityAttributeName,
    entityAttributeTypeName,
    entityInstanceId,
    entityListItemName,
    entityRef,
    entityTypeName,
    firstName,
    forumMessageName,
    forumNames,
    forumThreadName,
    harmonizedTariffScheduleCodeName,
    inet4Address,
    inventoryConditionName,
    inventorySerialized,
    isCommercial,
    isExtensible,
    itemAccountingCategoryName,
    itemCategoryName,
    itemDeliveryTypeName,
    itemInventoryTypeName,
    itemName,
    itemNameAndAliases,
    itemPriceTypeName,
    itemPurchasingCategoryName,
    itemTypeName,
    itemUseTypeName,
    keepAllHistory,
    lastName,
    maximumUnitPrice,
    middleName,
    minimumUnitPrice,
    modifiedTime,
    name,
    nameSuffix,
    offerName,
    overview,
    parentContentCategoryName,
    parentSecurityRoleGroupName,
    partyEmployeeName,
    partyName,
    partyNames,
    partyTypeNames,
    personalTitle,
    postalCode,
    postalCodeGeoCodeName,
    postedTime,
    purchaseOrderStartTime,
    purchaseOrderEndTime,
    salesOrderStartTime,
    salesOrderEndTime,
    securityRoleGroupName,
    securityRoleName,
    shippingChargeExempt,
    shippingEndTime,
    shippingMethodName,
    shippingStartTime,
    state,
    stateGeoCodeName,
    telephoneExtension,
    telephoneNumber,
    trackRevisions,
    unitOfMeasureKindName,
    unitOfMeasureTypeName,
    unitPrice,
    unitPriceIncrement,
    url,
    useName,
    useTypeName,
    vendorName,
    vendorTypeName,
    warehouseName,
    warehouseTypeName,

}
