// --------------------------------------------------------------------------------
// Copyright 2002-2025 Echo Three, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------------------

package com.echothree.model.control.graphql.server.util;

import com.echothree.util.common.form.BaseForm;
import com.echothree.util.server.control.GraphQlSecurityCommand;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;

public interface GraphQlSecurityUtils {

    private static <F extends BaseForm> Constructor<?> findConstructor(final Class<? extends GraphQlSecurityCommand<F>> command) {
        Constructor<?> foundCtor = null;
        var allConstructors = command.getDeclaredConstructors();

        for(var ctor : allConstructors) {
            var pType = ctor.getParameterTypes();

            if(pType.length == 0) {
                foundCtor = ctor;
                break;
            }
        }

        if(foundCtor == null) {
            throw new RuntimeException("command does not implement the required Constructor");
        }

        return foundCtor;
    }

    static <F extends BaseForm> boolean hasAccess(final GraphQlExecutionContext context, final Class<? extends GraphQlSecurityCommand<F>> command, final F form) {
        boolean hasAccess;

        try {
            var ctor = findConstructor(command); // Search for the Constructor that's required here
            var commandInstance = ctor.newInstance();
            var graphQlSecurityCommand = (GraphQlSecurityCommand<F>) commandInstance;

            // Execute the instantiated command's security check function for the current user.
            graphQlSecurityCommand.security(context.getUserVisitPK(), form);

            // User will have access to this GraphQL field as long as there are no security
            // messages (errors) generated by the command.
            hasAccess = !graphQlSecurityCommand.hasSecurityMessages();
        } catch(InstantiationException | IllegalAccessException | InvocationTargetException e) {
            throw new RuntimeException(e);
        }

        return hasAccess;
    }
    
}
