image: echothree/build:latest

variables:
  ANT_OPTS: "-Xmx5120m"

stages:
  - build

build:
  stage: build
  script:
    - pushd ..
    - ln -s $WILDFLY_HOME wildfly-latest
    - popd
    - ant setup-ivy
    - ant complete
  artifacts:
    paths:
      - build/ears/echothree.ear
      - build/jars/echothree-client.jar
      - build/ui/web/cms/war/cms.war
      - build/ui/web/letter/war/letter.war
      - build/ui/web/main/war/main.war
      - build/service/graphql/war/graphql.war
      - build/service/job/jar/echothree-job.jar
      - build/ui/cli/database/jar/database.jar
      - build/ui/cli/dataloader/jar/dataloader.jar
      - build/ui/cli/mailtransfer/jar/mailtransfer.jar
      - build/lib/mysql-connector-java.jar
      - build/lib/guava.jar
      - build/lib/commons-cli.jar
      - build/lib/commons-lang.jar
      - build/lib/commons-configuration.jar
      - build/lib/commons-beanutils.jar
      - build/lib/commons-logging.jar
      - build/lib/commons-collections.jar
      - build/lib/log4j.jar
      - build/lib/slf4j-api.jar
      - build/lib/slf4j-log4j12.jar
      - build/lib/wildfly-client-all.jar
    expire_in: 1 week

