image: gitlab.echothree.com:5050/containers/jdk-build-tools:latest

cache:
  paths:
    - .ivy2/cache

variables:
  ANT_OPTS: "-Xmx6150m -Divy.default.ivy.user.dir=$CI_PROJECT_DIR/.ivy2"

stages:
  - build

build:
  stage: build
  script:
    - ant setup-ivy
    - ant complete
  artifacts:
    paths:
      - build/ears/echothree.ear
      - build/jars/echothree-client.jar
      - build/jars/echothree-client-javadoc.jar
      - build/jars/echothree-client-sources.jar
      - build/ui/web/cms/war/cms.war
      - build/ui/web/letter/war/letter.war
      - build/ui/web/main/war/main.war
      - build/service/graphql/war/graphql.war
      - build/service/job/jar/echothree-job.jar
      - build/ui/cli/database/jar/database.jar
      - build/ui/cli/dataloader/jar/dataloader.jar
      - build/ui/cli/mailtransfer/jar/mailtransfer.jar
      - build/lib/jooq.jar
      - build/lib/jooq-codegen.jar
      - build/lib/jooq-meta.jar
      - build/lib/jaxb-api.jar
      - build/lib/r2dbc-spi.jar
      - build/lib/reactive-streams.jar
      - build/lib/mysql-connector-java.jar
      - build/lib/nekohtml.jar
      - build/lib/javax.mail.jar
      - build/lib/activation.jar
      - build/lib/javax.activation-api.jar
      - build/lib/xercesImpl.jar
      - build/lib/guava.jar
      - build/lib/commons-cli.jar
      - build/lib/commons-lang.jar
      - build/lib/commons-configuration.jar
      - build/lib/commons-beanutils.jar
      - build/lib/commons-logging.jar
      - build/lib/commons-collections.jar
      - build/lib/reload4j.jar
      - build/lib/slf4j-api.jar
      - build/lib/slf4j-reload4j.jar
      - build/lib/wildfly-client-all.jar
    expire_in: 1 week

